### ISSUE TITLE
CSS - sizing in pixels and header image

### ISSUE THREAD

**Issue by jbolmarcich** [LIS462Omeka/KillgroveTheme#12]
Browsing through CSS as implemented with Chrome DevTools, it looks like there are a number of places where sizing is done absolutely (in pixels). Should we make these all relative?

On the header display, it doesn't seem very responsive, and so I was wondering if changing it from a static image of
- [background+stamp+border] image
- title

to
- background
- stamp image
- border
- title

so that each piece can move as needed for different displays.

Nikki - can you point me to your original background image for the header, as well as for the border? I can play with this tomorrow.

Thoughts?

**Comment by nikki-t** [comment]
Hi Jen, I was thinking of something similar because I have tried the site out in different browsers and the responsiveness is different for everything. I did notice that one of the forums pointed to using contain in the background-size:

http://omeka.org/forums/topic/default-thanksroy-theme-tweaks

I have noted in the CSS any changes I made so you should be able to see what I did rather easily.
The header image is in the /images folder. 

I have attached the stamp logo
![stamplogo](https://cloud.githubusercontent.com/assets/17799906/13908739/9de1f3fe-eedf-11e5-907b-6136e72366ab.png)
. It might be possible for the stamp to be uploaded as the logo and then the CSS changed to flip it over to the right side. Let me know if you need the stamp to be bigger.

The border is a part of the header image so if you need me to make it separate file let me know!

**Comment by jbolmarcich** [comment]
I know the border's currently part of the header image, but had assumed you
had flattened an image you created in Photoshop or similar, so was more
interested in what you started with rather than what you finished.
